# Generated by Django 5.0.4 on 2024-09-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDepartments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Offdays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30, null=True)),
                ('date', models.DateField()),
                ('days_spanning', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=40)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_management.employeedepartments'),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=30)),
                ('used_leaves', models.IntegerField(default=0)),
                ('total_leaves', models.IntegerField(default=40)),
                ('leave_balance', models.IntegerField(default=40)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=300)),
                ('phone_no', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('role', models.CharField(max_length=30, null=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='leave_management.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.manager')),
            ],
        ),
        migrations.AddField(
            model_name='employeedepartments',
            name='hod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.manager'),
        ),
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_status', models.CharField(max_length=30)),
                ('comments', models.TextField(blank=True, null=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.leaves')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.manager')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=40)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.manager')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerDepartments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('hod', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.employee')),
            ],
        ),
    ]
