# Generated by Django 5.0.4 on 2024-09-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_populate_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedepartments',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.manager'),
        ),
    ]
