# Generated by Django 5.0.4 on 2024-09-30 11:52

from django.db import migrations


# Generated by Django 5.0.4 on 2024-09-28 09:20

from django.db import migrations, transaction

def add_employees_and_managers(apps, schema_editor):
    Employee = apps.get_model('leave_management', 'Employee')
    Manager = apps.get_model('leave_management', 'Manager')

    # Add Managers and Employees
    with transaction.atomic():
        try:
            # Add Managers
            john = Manager.objects.create(
                first_name='John',
                last_name='Doe',
                email='john.doe@example.com',
                phone_no='1234567890',
                gender='Male',
                age=35,
                dob='1989-01-01',
                registration_date='2024-09-28',
                role='HR Manager'
            )
            
            jane = Manager.objects.create(
                first_name='Jane',
                last_name='Smith',
                email='jane.smith@example.com',
                phone_no='0987654321',
                gender='Female',
                age=30,
                dob='1994-01-01',
                registration_date='2024-09-28',
                role='IT Manager'
            )

            # Add Employees
            alice = Employee.objects.create(
                first_name='Alice',
                last_name='Johnson',
                email='alice.johnson@example.com',
                phone_no='1112223333',
                gender='Female',
                age=28,
                dob='1996-02-02',
                department=None,  # Assuming departments are added separately or can be null
                registration_date='2024-09-28',
            )

            bob = Employee.objects.create(
                first_name='Bob',
                last_name='Williams',
                email='bob.williams@example.com',
                phone_no='4445556666',
                gender='Male',
                age=32,
                dob='1992-03-03',
                department=None,  # Assuming departments are added separately or can be null
                registration_date='2024-09-28',
            )

        except Exception as e:
            print(f"An error occurred: {e}")
            raise  # Reraise the exception to maintain transaction integrity


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_employeedepartments_hod'),
    ]

    operations = [
        migrations.RunPython(add_employees_and_managers),
    ]